# Generated by Django 2.1.5 on 2019-04-09 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20190405_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='desc',
        ),
        migrations.AddField(
            model_name='forfait',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
