# Generated by Django 2.1.5 on 2019-04-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20190409_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='niche',
            new_name='domain',
        ),
    ]
