# Generated by Django 2.1.5 on 2019-04-16 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_auto_20190416_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
