# Generated by Django 2.1.5 on 2019-04-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_search_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
